### ISSUE TITLE
Wrap in order to wait for response to be fetched

### ISSUE THREAD

**Issue by Arthurmtro** [jamesikjo/quiz-of-luchador#3]
https://github.com/jamesikjo/quiz-of-luchador/blob/982047001f314929b20dd94c0aa4e0b201887e92/client/src/components/Question/RevealAnswer/RevealAnswer.tsx#L61

You should add placeholder when answer = undefined or Promise loading

**Comment by jamesikjo** [comment]
Fixed flicking issue: 7f3bec16aef2b0c3a9f5991b52cc081b00df3a21

If you know of another solution, please let me know.
