### ISSUE TITLE
Maybe wrap types in other file

### ISSUE THREAD

**Issue by Arthurmtro** [jamesikjo/quiz-of-luchador#4]
https://github.com/jamesikjo/quiz-of-luchador/blob/982047001f314929b20dd94c0aa4e0b201887e92/client/src/components/Question/Question.tsx#L8-L15

like this

myComponent.types.ts

so it will be cleaner :)

**Comment by jamesikjo** [comment]
Combined types into a separate file: 74bb91121b5b26908ba888a3f172e7c977faa954
